import { Meteor } from 'meteor/meteor';

/**
 * PayTM Cordova Service
 * Handles native PayTM All-in-One SDK integration for Cordova/mobile apps.
 * This class is designed to initiate payments after the server has generated the txnToken.
 */

class PayTMCordovaService {
  /**
   * Start a payment transaction using PayTM All-in-One SDK
   * * @param {Object} params - Payment parameters
   * @param {string} params.txToken - Transaction token generated by the server.
   * @param {string} params.amount - Payment amount (e.g., "10.00").
   * @param {string} params.orderId - Unique Order ID.
   * @param {string} params.mid - Merchant ID.
   * @param {string} params.callbackUrl - The server-side callback URL for payment response. 
   * MUST match the URL used for txnToken generation.
   * @param {Function} onTransactionComplete - Callback for transaction result (success or status-driven failure). 
   * Receives the standardized transaction response object.
   * @param {Function} onError - Callback for true SDK errors (plugin not found, user cancellation before status, etc.).
   * Receives an error object { status, message, code, originalError }.
   */
  startPayment({ txToken, amount, orderId, mid, callbackUrl }, onTransactionComplete, onError) {
    console.log('PayTM startPayment called with:', { 
      orderId, 
      amount, 
      mid,
      hasTxToken: !!txToken,
      callbackUrl: callbackUrl ? '***' + callbackUrl.substring(callbackUrl.length - 20) : 'missing'
    });
    
    if (!Meteor.isCordova) {
      const error = new Error('PayTM Cordova plugin is only available in Cordova environment');
      console.error('PayTM Error - Not in Cordova:', error);
      onError({ 
        status: 'error',
        message: 'PayTM is only available in mobile app',
        code: 'CORDOVA_REQUIRED',
        originalError: error
      });
      return;
    }

    // --- SDK and Method Availability Checks ---
    if (!window.AllInOneSDK || typeof window.AllInOneSDK.startTransaction !== 'function') {
      const sdkError = new Error('PayTM AllInOneSDK or startTransaction method not found');
      console.error('PayTM Error - SDK not found:', sdkError);
      onError({ 
        status: 'error',
        message: 'Payment service not available or improperly initialized. Please check plugin installation.',
        code: 'SDK_NOT_FOUND',
        originalError: sdkError
      });
      return;
    }

    // --- Parameter Validation ---
    if (!txToken || !callbackUrl || !orderId || !mid || !amount) {
      const error = new Error('Missing required parameters: txToken, callbackUrl, orderId, mid, or amount.');
      console.error('PayTM Error - Missing configuration:', error);
      onError({
        status: 'error',
        message: 'Payment configuration error: Missing required transaction data.',
        code: 'INVALID_CONFIGURATION',
        originalError: error
      });
      return;
    }

    // --- Prepare payment parameters for Cordova plugin ---
    // NOTE: Only client-side required params are included. 
    // Server-side params (website, channelId, industryTypeId, apiBaseUrl) are excluded.
    const paymentParams = {
      mid,
      orderId,
      txnToken: txToken,
      amount: amount.toString(), // Amount must be a string
      isStaging: true, // Required by cordova-paytmpayments-allinonesdk
      restrictAppInvoke: false, // Allows web fallback if PayTM app is not installed
      callbackUrl: callbackUrl // MUST match the URL used in the server-side token generation
    };
    
    console.log('Starting PayTM Cordova payment with secure params:', {
      ...paymentParams,
      txnToken: txToken ? '***' + txToken.slice(-4) : 'MISSING',
    });
    
    // Start payment using Cordova plugin
    window.AllInOneSDK.startTransaction(
      paymentParams,
      // Success Callback (Handles TXN_SUCCESS and TXN_FAILURE responses)
      (response) => {
        console.log('PayTM Cordova payment response:', JSON.stringify(response));
        
        // Parse the response if it's in the newer plugin format with stringified response
        let parsedResponse = response;
        if (response.response && typeof response.response === 'string') {
          try {
            parsedResponse = JSON.parse(response.response);
          } catch (e) {
            console.error('Failed to parse PayTM response:', e);
            parsedResponse = response;
          }
        }
        
        // Use a standardized response format for consistency across web/cordova
        const standardizedResponse = this._standardizeResponse(parsedResponse);

        // Ensure ORDERID is present (inject from closure if missing in response)
        if (!standardizedResponse.ORDERID) {
            standardizedResponse.ORDERID = orderId;
        }
        
        // Always call onTransactionComplete for any response that has a status
        // This includes both successful transactions and status-driven failures (e.g., TXN_FAILURE)
        if (standardizedResponse && standardizedResponse.STATUS) {
          onTransactionComplete(standardizedResponse);
        } else {
          // Fallback for unexpected successful response structure
          console.warn('Unexpected successful PayTM response format (no STATUS):', response);
          onTransactionComplete({
            STATUS: 'TXN_FAILURE',
            RESPCODE: '400',
            RESPMSG: 'Unexpected response from payment gateway (No Status Code)',
            ...response // Include original response for debugging
          });
        }
      },
      // Error Callback (Handles true SDK errors like user cancellation or initialization issues)
      (error) => {
        console.error('PayTM Cordova SDK error:', error);
        
        // If the error object contains a STATUS, it's actually a transaction status failure, 
        // and should be handled by onTransactionComplete.
        if (error && (error.STATUS || error.status)) {
          console.warn('Received transaction status in error callback, processing as transaction response.');
          onTransactionComplete(this._standardizeResponse(error));
        } else {
          // True SDK Error (e.g., plugin initialization failure, user canceled before status)
          onError({
            status: 'error',
            code: 'SDK_ERROR',
            message: error.message || 'Payment processing failed or was cancelled by user.',
            originalError: error
          });
        }
      }
    );
  }

  /**
   * Standardize PayTM Cordova response to match a consistent format.
   * This handles varying casing/naming conventions between web and Cordova SDKs.
   * @private
   */
  _standardizeResponse(cordovaResponse) {
    // Attempt to standardize common fields
    return {
      STATUS: cordovaResponse.STATUS || cordovaResponse.status || 'TXN_FAILURE',
      TXNAMOUNT: cordovaResponse.TXNAMOUNT || cordovaResponse.TXNAMT || cordovaResponse.amount || '0',
      TXNID: cordovaResponse.TXNID || cordovaResponse.txnId || '',
      CHECKSUMHASH: cordovaResponse.CHECKSUMHASH || cordovaResponse.checksumHash || '',
      RESPCODE: cordovaResponse.RESPCODE || cordovaResponse.respCode || '400',
      RESPMSG: cordovaResponse.RESPMSG || cordovaResponse.respMsg || cordovaResponse.message || 'Transaction failed',
      ORDERID: cordovaResponse.ORDERID || cordovaResponse.orderId || '',
      PAYMENTMODE: cordovaResponse.PAYMENTMODE || cordovaResponse.paymentMode || 'OTHER',
      // Include the full original response for full fidelity
      _original: cordovaResponse
    };
  }

  /**
   * Check if PayTM Cordova plugin is available
   * @returns {boolean}
   */
  isAvailable() {
    return Meteor.isCordova && window.AllInOneSDK && typeof window.AllInOneSDK.startTransaction === 'function';
  }

  /**
   * Verify payment status with the server
   * @param {string} orderId - The order ID to verify
   * @returns {Promise<Object>} - The payment status
   */
  verifyPaymentStatus(orderId) {
    return new Promise((resolve, reject) => {
      if (!orderId) {
        return reject(new Error('Order ID is required for payment verification'));
      }

      // Add a small delay to ensure the payment has been processed
      setTimeout(() => {
        Meteor.call('payment.paytm.verifyPayment', orderId, (error, result) => {
          if (error) {
            console.error('Error verifying payment:', error);
            return reject(error);
          }
          resolve(result);
        });
      }, 2000); // 2 second delay before verification
    });
  }
}

// Export singleton instance
export default new PayTMCordovaService();