// Mocks generated by Mockito 5.4.4 from annotations
// in suvai/test/screens/checkout_notification_requirement_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:suvai/models/auth_state.dart' as _i11;
import 'package:suvai/models/order.dart' as _i13;
import 'package:suvai/models/product.dart' as _i4;
import 'package:suvai/models/user.dart' as _i10;
import 'package:suvai/providers/auth_provider.dart' as _i9;
import 'package:suvai/providers/cart_provider.dart' as _i3;
import 'package:suvai/screens/public/checkout_screen.dart' as _i7;
import 'package:suvai/services/meteor_client.dart' as _i12;
import 'package:suvai/services/order_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrderService_0 extends _i1.SmartFake implements _i2.OrderService {
  _FakeOrderService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CartProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartProvider extends _i1.Mock implements _i3.CartProvider {
  MockCartProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.CartItem> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i4.CartItem>[],
      ) as List<_i4.CartItem>);

  @override
  List<_i4.CartItem> get removedItems => (super.noSuchMethod(
        Invocation.getter(#removedItems),
        returnValue: <_i4.CartItem>[],
      ) as List<_i4.CartItem>);

  @override
  List<_i4.CartItem> get availableItems => (super.noSuchMethod(
        Invocation.getter(#availableItems),
        returnValue: <_i4.CartItem>[],
      ) as List<_i4.CartItem>);

  @override
  double get totalAmount => (super.noSuchMethod(
        Invocation.getter(#totalAmount),
        returnValue: 0.0,
      ) as double);

  @override
  int get itemCount => (super.noSuchMethod(
        Invocation.getter(#itemCount),
        returnValue: 0,
      ) as int);

  @override
  String get lastOrderId => (super.noSuchMethod(
        Invocation.getter(#lastOrderId),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#lastOrderId),
        ),
      ) as String);

  @override
  _i2.OrderService get orderService => (super.noSuchMethod(
        Invocation.getter(#orderService),
        returnValue: _FakeOrderService_0(
          this,
          Invocation.getter(#orderService),
        ),
      ) as _i2.OrderService);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> initializeProducts(List<_i4.Product>? products) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeProducts,
          [products],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void updateProductAvailability(List<_i4.Product>? currentProductList) =>
      super.noSuchMethod(
        Invocation.method(
          #updateProductAvailability,
          [currentProductList],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, List<_i4.CartItem>> separateItemsByAvailability(
          List<_i4.Product>? currentProductList) =>
      (super.noSuchMethod(
        Invocation.method(
          #separateItemsByAvailability,
          [currentProductList],
        ),
        returnValue: <String, List<_i4.CartItem>>{},
      ) as Map<String, List<_i4.CartItem>>);

  @override
  _i6.Future<void> loadCart() => (super.noSuchMethod(
        Invocation.method(
          #loadCart,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addItem(
    _i4.Product? product,
    double? quantity, {
    double? selectedUnit = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [
            product,
            quantity,
          ],
          {#selectedUnit: selectedUnit},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> moveItemToRemoved(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #moveItemToRemoved,
          [productId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeItem(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #removeItem,
          [productId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeItemByUnit(
    String? productId,
    double? selectedUnit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeItemByUnit,
          [
            productId,
            selectedUnit,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateQuantity(
    String? productId,
    double? quantity, {
    double? selectedUnit = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuantity,
          [
            productId,
            quantity,
          ],
          {#selectedUnit: selectedUnit},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateItemUnit(
    String? productId,
    double? newSelectedUnit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemUnit,
          [
            productId,
            newSelectedUnit,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> commitRemovedItems() => (super.noSuchMethod(
        Invocation.method(
          #commitRemovedItems,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearCart() => (super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String> placeOrder(
    _i7.CheckoutData? checkoutData, {
    bool? clearCart = true,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #placeOrder,
          [checkoutData],
          {
            #clearCart: clearCart,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #placeOrder,
            [checkoutData],
            {
              #clearCart: clearCart,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i9.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set currentUserForTesting(_i10.User? value) => super.noSuchMethod(
        Invocation.setter(
          #currentUserForTesting,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set errorForTesting(String? value) => super.noSuchMethod(
        Invocation.setter(
          #errorForTesting,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.AuthState get authState => (super.noSuchMethod(
        Invocation.getter(#authState),
        returnValue: _i11.AuthState.initial,
      ) as _i11.AuthState);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get isGuest => (super.noSuchMethod(
        Invocation.getter(#isGuest),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoggedInUser => (super.noSuchMethod(
        Invocation.getter(#isLoggedInUser),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> signup({
    required String? phone,
    required String? password,
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? deliveryAddress,
    required String? deliveryPincode,
    String? eatingHealthyMeaning,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [],
          {
            #phone: phone,
            #password: password,
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #deliveryAddress: deliveryAddress,
            #deliveryPincode: deliveryPincode,
            #eatingHealthyMeaning: eatingHealthyMeaning,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> login(
    String? phone,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            phone,
            password,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> restoreAuthState() => (super.noSuchMethod(
        Invocation.method(
          #restoreAuthState,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> continueAsGuest() => (super.noSuchMethod(
        Invocation.method(
          #continueAsGuest,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateProfile({
    required String? emailAddress,
    String? salutation,
    String? firstName,
    String? lastName,
    String? whMobilePhone,
    String? deliveryAddress,
    String? deliveryPincode,
    String? dietPreference,
    String? packingPreference,
    String? productUpdatePreference,
    bool? clearCartAfterOrder,
    String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #emailAddress: emailAddress,
            #salutation: salutation,
            #firstName: firstName,
            #lastName: lastName,
            #whMobilePhone: whMobilePhone,
            #deliveryAddress: deliveryAddress,
            #deliveryPincode: deliveryPincode,
            #dietPreference: dietPreference,
            #packingPreference: packingPreference,
            #productUpdatePreference: productUpdatePreference,
            #clearCartAfterOrder: clearCartAfterOrder,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OrderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderService extends _i1.Mock implements _i2.OrderService {
  MockOrderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setMeteorClient(_i12.MeteorClient? client) => super.noSuchMethod(
        Invocation.method(
          #setMeteorClient,
          [client],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<Map<String, String>> fetchStatusColors() => (super.noSuchMethod(
        Invocation.method(
          #fetchStatusColors,
          [],
        ),
        returnValue: _i6.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<String> getStatusColor(String? statusName) => (super.noSuchMethod(
        Invocation.method(
          #getStatusColor,
          [statusName],
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getStatusColor,
            [statusName],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<bool> checkPhoneExists(String? phone) => (super.noSuchMethod(
        Invocation.method(
          #checkPhoneExists,
          [phone],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<String> submitOrder(
    _i7.CheckoutData? data, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitOrder,
          [data],
          {#userId: userId},
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #submitOrder,
            [data],
            {#userId: userId},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i13.Order?> getOrderStatus(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderStatus,
          [orderId],
        ),
        returnValue: _i6.Future<_i13.Order?>.value(),
      ) as _i6.Future<_i13.Order?>);

  @override
  _i6.Future<List<_i13.Order>> fetchMyOrders(
          {bool? includeCompletedOrders = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMyOrders,
          [],
          {#includeCompletedOrders: includeCompletedOrders},
        ),
        returnValue: _i6.Future<List<_i13.Order>>.value(<_i13.Order>[]),
      ) as _i6.Future<List<_i13.Order>>);

  @override
  _i6.Future<List<dynamic>> fetchMyInvoices() => (super.noSuchMethod(
        Invocation.method(
          #fetchMyInvoices,
          [],
        ),
        returnValue: _i6.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i6.Future<List<dynamic>>);

  @override
  _i6.Future<List<_i13.Order>> fetchPendingOrders() => (super.noSuchMethod(
        Invocation.method(
          #fetchPendingOrders,
          [],
        ),
        returnValue: _i6.Future<List<_i13.Order>>.value(<_i13.Order>[]),
      ) as _i6.Future<List<_i13.Order>>);

  @override
  _i6.Future<bool> cancelOrder(_i13.Order? order) => (super.noSuchMethod(
        Invocation.method(
          #cancelOrder,
          [order],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<dynamic> fetchInvoiceDetails(String? invoiceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchInvoiceDetails,
          [invoiceId],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<void> refreshOrders({bool? includeCompletedOrders = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshOrders,
          [],
          {#includeCompletedOrders: includeCompletedOrders},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<dynamic>> fetchCreditNotes() => (super.noSuchMethod(
        Invocation.method(
          #fetchCreditNotes,
          [],
        ),
        returnValue: _i6.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i6.Future<List<dynamic>>);

  @override
  _i6.Future<dynamic> fetchCreditNote(String? creditNoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCreditNote,
          [creditNoteId],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
}
