const Events = {
  ORDER_PAGE_EXPAND: 'ORDER_PAGE_EXPAND',
  NAVIGATE_PAGE: 'NAVIGATE_PAGE',
  ADREFERRAL_PAGE: 'ADREFERRAL_PAGE',
  ADREFERRAL_PAGE_PC_300_250: 'ADREFERRAL_PAGE_PC_300_250',
  ADREFERRAL_PAGE_PC_728_90: 'ADREFERRAL_PAGE_PC_728_90',
  ADREFERRAL_PAGE_PC_300_50: 'ADREFERRAL_PAGE_PC_300_50',
  NAVIGATE_SIGNUP_PAGE: 'NAVIGATE_SIGNUP_PAGE',
};

export default Events;
